# This is a basic workflow to help you get started with Actions

name: SCRAPE GRT

# Controls when the workflow will run
on:
  schedule:
    - cron: '30 3 * * *' # Runs every day at 3:30 AM UTC/9.00 AM IST
  workflow_dispatch: # Allows manual trigger

env: # Define global environment variables here
  SEND_FROM: ${{ secrets.SEND_FROM }}
  APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
  SEND_TO: ${{ secrets.SEND_TO }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scrape_goldrate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
             
#      - name: Download CSV artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: grt_rates
#          path: ./

      - name: Scrape and send email
        run: |
          pip install -r requirements.txt
          playwright install chromium
          python scrape_grtrates.py

      - name: Upload CSV file
        uses: actions/upload-artifact@v3
        with:
          name: grt_rates
          path: grt_rates.csv
          retention-days: 5

      - name: Upload Screenshot file
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: screenshot.png
          retention-days: 1

          
